### ISSUE TITLE
No images are generated and we stay on an endless loop

### ISSUE THREAD

**Issue by jdragonx** [Waenara/bing-create#2]
When generating images, sometimes no images are returned, even though Bing's response is successful. This causes the cycle generation to be stuck on an endless loop because the current prompt generates 0 images, but the cycle will only stop when the desired number is reached or surpassed.

This is probably caused by the prompt being deemed unsafe by the image generator model itself (instead of the guardrails model that seems to be in front of it).

I've created a PR for this.

https://github.com/Waenara/bing-create/pull/1

**Comment by spupuz** [comment]
i got a similar problem don't know if it is the same 

https://github.com/Waenara/bing-create/issues/3
